name: plankton-api
services:
- name: api
  github:
    branch: main
    deploy_on_push: true
    repo: your-username/your-repo-name
  dockerfile_path: Dockerfile
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xxs
  envs:
  - key: SECRET_KEY
    scope: RUN_TIME
    type: SECRET
  - key: DATABASE_URL
    scope: RUN_TIME
    type: SECRET